//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAttendence
    {
        public int ClassAttendenceId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public int CourseId { get; set; }
    
        public virtual StudentAttendence StudentAttendence { get; set; }
        public virtual Course Course { get; set; }
    }
}
