//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB40Entities4 : DbContext
    {
        public DB40Entities4()
            : base("name=DB40Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Chalan> Chalans { get; set; }
        public virtual DbSet<ClassAttendence> ClassAttendences { get; set; }
        public virtual DbSet<complaint> complaints { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentCourseRelation> DepartmentCourseRelations { get; set; }
        public virtual DbSet<DepartmentInstructorRelation> DepartmentInstructorRelations { get; set; }
        public virtual DbSet<DepartmentStudentRelation> DepartmentStudentRelations { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<InstructorCourseRelation> InstructorCourseRelations { get; set; }
        public virtual DbSet<InstructorStudentRelation> InstructorStudentRelations { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<ParentStudentRelation> ParentStudentRelations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentAttendence> StudentAttendences { get; set; }
        public virtual DbSet<StudentChalanRelation> StudentChalanRelations { get; set; }
        public virtual DbSet<StudentcomplaintRelation> StudentcomplaintRelations { get; set; }
        public virtual DbSet<StudentEventRelation> StudentEventRelations { get; set; }
        public virtual DbSet<StudentHostelRelation> StudentHostelRelations { get; set; }
        public virtual DbSet<StudentRegSubjectRelation> StudentRegSubjectRelations { get; set; }
        public virtual DbSet<StudentResult> StudentResults { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
