//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendence
    {
        public int AttendenceId { get; set; }
        public int StudentId { get; set; }
        public int AttendenceStatus { get; set; }
    
        public virtual ClassAttendence ClassAttendence { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Student Student { get; set; }
    }
}
